"files": [
  {
    "source": "/AutoSite/**.resx",
    "translation": "/AutoSite/%file_name%.%two_letters_code%.resx",
    "ignore": [
      "/AutoSite/%file_name%.%two_letters_code%.resx", #ignore the translated files
    ]
  },
  {
    "source": "/AutoSite/My Project/Resources.resx",
    "translation": "/AutoSite/My Project/Resources.%two_letters_code%.resx"
  }
]
